name : FOR LMX
on :     
  workflow_dispatch: 
  schedule:  
  # 代表国际标准时间23点10分，北京时间需要+8小时，代表北京时间上午7点01运行 
  - cron: '01 23 * * *' 
jobs: 
   #将工作流程中运行的所有作业组合在一起 
 build: 
   #定义名为 build 的作业。 子键将定义作业的属性  
   runs-on: ubuntu-latest  
   name: send morning to my dear
   
   steps: 
   - name: Set up Python 3.9 
     uses: actions/checkout@v2 
  
   - name: sender
     uses: actions/setup-python@v2
     with:
        python-version: '3.x'
        architecture: 'x64'
   - run: pip install -r ./requirements.txt && python ./main.py
